version: '3.8'

volumes:
  pg-data:
  
services:
  api:
    build: .
    ports:
      - "4000:4000"
    restart: on-failure
    depends_on:
      - pg
    env_file:
      - ./.env
  
  pg:
    image: postgres:14.5-alpine
    ports:
      - "5433:5432"
    restart: on-failure
    environment:
      - POSTGRES_USER=greenlight
      - POSTGRES_PASSWORD=pa55word
      - POSTGRES_DB=greenlight
    volumes:
      - pg-data:/var/lib/postgresql/data    